kind: pipeline
type: docker
name: CI/CD Backend

steps:
  - name: Build & Push Docker Image
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKERHUB_USERNAME # pragma: allowlist secret
      password: 
        from_secret: DOCKERHUB_TOKEN # pragma: allowlist secret
      repo: nhathuyd4hp/qrapp-backend
      cache_from:
        - nhathuyd4hp/qrapp-backend:latest
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      tags:
        - latest
  - name: Deployment
    image: ghcr.io/appleboy/drone-ssh
    settings:
      host: 
        from_secret: SSH_HOST # pragma: allowlist secret
      username: root
      password:
        from_secret: SSH_PASSWORD # pragma: allowlist secret
      port: 22
      command_timeout: 30s
      script:
        - cd ~/Document/QRApp
        - mkdir -p Backend
        - cd ~/Document/QRApp/Backend
        - git clone https://github.com/QRBusiness/QRApp-BackEnd.git . || true
        - git restore .
        - git pull origin main
        - docker compose up -d
trigger:
  branch:
    - main
  event:
    - push
    - custom
