############################################
# 🧱 PIPELINE 1: Build & Push Docker Image
############################################
kind: pipeline
type: docker
name: CI Backend

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Build & Push Docker Image
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKERHUB_USERNAME # pragma: allowlist secret
      password: 
        from_secret: DOCKERHUB_TOKEN # pragma: allowlist secret
      repo: nhathuyd4hp/qrapp-backend
      cache_from:
        - nhathuyd4hp/qrapp-backend:latest
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      tags:
        - latest

---

########################################
# 🚀 PIPELINE 2: Deployment via SSH
########################################
kind: pipeline
type: docker
name: CD Backend

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: Deployment
    image: ghcr.io/appleboy/drone-ssh
    settings:
      host: 
        from_secret: SSH_HOST # pragma: allowlist secret
      username: root
      password:
        from_secret: SSH_PASSWORD # pragma: allowlist secret
      port: 22
      command_timeout: 600s
      script:
        - cd ~/Document/QRApp
        - mkdir -p Backend
        - cd ~/Document/QRApp/Backend
        - git clone https://github.com/QRBusiness/QRApp-BackEnd.git . || true
        - git restore . || true
        - git pull origin main || true
        - |
          cat <<EOF > .env
          ACCESS_KEY=${ACCESS_KEY}
          REFRESH_KEY=${REFRESH_KEY}
          MONGO_URL=${MONGO_URL}
          REDIS_URL=${REDIS_URL}
          MINIO_ENDPOINT=${MINIO_ENDPOINT}
          MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
          MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
          EOF
        - docker compose up -d
    environment:
      ACCESS_KEY:
        from_secret: ACCESS_KEY # pragma: allowlist secret
      REFRESH_KEY:
        from_secret: REFRESH_KEY # pragma: allowlist secret
      MONGO_URL:
        from_secret: MONGO_URL # pragma: allowlist secret
      REDIS_URL:
        from_secret: REDIS_URL # pragma: allowlist secret
      MINIO_ENDPOINT:
        from_secret: MINIO_ENDPOINT # pragma: allowlist secret
      MINIO_ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY # pragma: allowlist secret
      MINIO_SECRET_KEY:
        from_secret: MINIO_SECRET_KEY # pragma: allowlist secret
