kind: pipeline
type: docker
name: build-and-push

steps:
  - name: docker-build-push
    image: plugins/docker
    settings:
      username: nhathuyd4hp # pragma: allowlist secret
      password: dckr_pat_HgNbPWj1SqMIH6Z-ex7IVYKjT-E # pragma: allowlist secret
      repo: nhathuyd4hp/myapp
      tags:
        - $DRONE_COMMIT_SHA
        - latest
trigger:
  branch:
    - main
  event:
    - push