kind: pipeline
type: docker
name: Docker-CI

steps:
  - name: Docker-CI
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKERHUB_USERNAME # pragma: allowlist secret
      password: 
        from_secret: DOCKERHUB_TOKEN # pragma: allowlist secret
      repo: nhathuyd4hp/qrapp-backend
      tags:
        - latest
  - name: Deployment
    image: ghcr.io/appleboy/drone-ssh
    settings:
      host: 
        from_secret: SSH_HOST # pragma: allowlist secret
      username: root
      password:
        from_secret: SSH_PASSWORD # pragma: allowlist secret
      port: 22
      command_timeout: 30s
      script:
        - echo "Hello World"
        - whoami
trigger:
  branch:
    - main
  event:
    - push
    - custom
