kind: pipeline
type: docker
name: Docker-CI

steps:
  - name: Docker-CI
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKERHUB_USERNAME # pragma: allowlist secret
      password: 
        from_secret: DOCKERHUB_TOKEN # pragma: allowlist secret
      repo: nhathuyd4hp/qrapp-backend-droneci
      tags:
        - latest
    when:
      paths:
        include:
          - app/**
trigger:
  branch:
    - main
  event:
    - push
    - custom
