services:
  qrapp-backend:
    image: nhathuyd4hp/qrapp-backend:latest
    container_name: api.qrapp
    pull_policy: always
    hostname: api.qrapp
    ports:
      - 8000:8000
    volumes:
      - /app/logs:/app/logs
    env_file:
        - .env

volumes:
  minio_data:
