services:
  redis:
    image: redis:latest
    container_name: QRSession
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: QRMySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Nh@thuyd4hp
      MYSQL_DATABASE: QRApp
      MYSQL_USER: nhathuyd4hp
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
