services:
  qrapp-backend:
    image: nhathuyd4hp/qrapp-backend:latest
    container_name: api.qrapp
    pull_policy: always
    volumes:
      - ./logs:/app/logs
    environment:
      TZ: Asia/Hong_Kong
    env_file:
        - .env
    networks:
        - QRNetwork
  nginx-backend:
    image: nginx:stable-alpine
    hostname: api.qrapp
    container_name: nginx.api.qrapp
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qrapp-backend
    networks:
      - QRNetwork

networks:
  QRNetwork:
    external: true
  # promtail:
  #   image: grafana/promtail:2.9.4
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yaml:/etc/promtail/promtail.yaml
  #     - ./logs:/app/logs
  #   command: -config.file=/etc/promtail/promtail.yaml
  #   depends_on:
  #     - qrapp-backend

  # loki:
  #   image: grafana/loki:2.9.4
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - loki
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
