services:
  redis:
    image: redis:7.2.5
    restart: always
    volumes:
      - ./redis/data:/data
    networks:
      - QRNetwork
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    restart: always
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    networks:
      - QRNetwork
    ports:
      - "9001:9001"
    command: server --console-address ":9001" /data

networks:
  QRNetwork:
    external: true
