
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi-log
          __path__: /app/logs/app.log
          app: qrapp
    
    pipeline_stages:
      # Stage 1: Parse log với regex
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| (?P<level>\w+)\s+\| (?P<logger>[\w\.:]+) \| (?P<json_data>\{.*\})$'
      
      # Stage 2: Parse JSON data từ phần cuối log
      - json:
          expressions:
            request_id: request_id
            host: host  
            user_agent: user_agent
            method: method
            path: path
            duration: duration
            status_code: status_code
            error: error
          source: json_data
      
      # Stage 3: Parse timestamp
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
      
      # Stage 4: Thêm labels để query dễ dàng
      - labels:
          level: level
          method: method
          status_code: status_code
          path: path
      
      # Stage 5: Output JSON structure cuối cùng
      - output:
          source: |
            {
              "timestamp": "{{ .timestamp }}",
              "level": "{{ .level }}",
              "logger": "{{ .logger }}",
              "request_id": "{{ .request_id }}",
              "host": "{{ .host }}",
              "user_agent": "{{ .user_agent }}",
              "method": "{{ .method }}",
              "path": "{{ .path }}",
              "duration": {{ .duration }},
              "status_code": {{ .status_code }},
              "error": {{ if .error }}"{{ .error }}"{{ else }}null{{ end }}
            }