server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi-log
          app: qrapp
          __path__: /app/logs/app.log

    pipeline_stages:
      # Stage 1: Cắt dòng log thành 4 phần: timestamp | level | logger | json_data
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| (?P<level>\w+)\s+\| (?P<logger>[^|]+) \| (?P<json_data>\{.*\})$'

      # Stage 2: Parse JSON ở phần json_data
      - json:
          source: json_data
          expressions:
            request_id: request_id
            method: method
            path: path
            host: host
            user_agent: user_agent
            duration: duration
            status_code: status_code
            error: error

      # Stage 3: Parse timestamp
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'

      # Stage 4: Chuyển vài field thành label để lọc nhanh
      - labels:
          level: level
          method: method
          path: path
          status_code: status_code
          request_id: request_id
