[project]
name = "eztable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pre-commit>=4.2.0",
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
    "pymysql>=1.1.1",
    "snowflake-id>=1.0.2",
    "sqlmodel>=0.0.24",
]
