name: Deployment
on:
  push:
    branches: ["dev"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.7.43.118
          username: root
          password: "@Admin123kcml"
          script: whoami
           
