name: Deployment

on:
  workflow_dispatch:
    push:
      branches: [main]
  workflow_run:
    workflows: ["Docker CI"] 
    branches: ["main"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s 
          script: |
            echo "Deploying..."
            whoami
