name: Deployment

on:
  workflow_dispatch:
    push:
      branches: [main]
  workflow_run:
    workflows: ["Docker CI"] 
    branches: ["main"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          cd ~/Document/QRApp/backend
          mkdir -p logs
          git fetch origin
          git checkout main
          git pull origin main
          docker compose up -d
