name: Deployment

on:
  workflow_run:
    workflows: ["Docker CI"] 
    branches: ["main"]
    types:
      - complete

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          timeout: 60s 
          script: |
            echo "Deploying..."
            whoami
