name: Docker CI

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "app/**"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "app/**"

jobs:
  build and push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag based on branch
        id: set-tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "tag=other" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image with tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qrapp-backend:${{ steps.set-tag.outputs.tag }}
